#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."


python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2009/sumners/support --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2009/verbeek-schmaltz/verbeek/generic-modules --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2009/verbeek-schmaltz/verbeek/instantiations/scheduling/circuit-switching-global --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2011/cowles-gamboa-sierpinski/support --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2011/krug-et-al/support --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2011/krug-et-al/support/Memory --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2011/krug-et-al/support/MinVisor --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2011/krug-et-al/support/Symbolic --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2011/krug-et-al/support/Utilities --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2011/krug-et-al/support/Y86 --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2011/swords-davis/support --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2011/verbeek-schmaltz --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2011/verbeek-schmaltz/sources --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2013/goel-hunt-kaufmann/support --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2013/hardin-hardin/support --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2013/joosten-van-gastel-schmaltz/books --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2013/van-gastel-schmaltz/books --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2013/verbeek-schmaltz/books --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2014/puri-ray-hao-xie/support --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2014/russinoff-oleary/support --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2015/chau-kaufmann-hunt/support --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2015/chau-kaufmann-hunt/support/riemann-integral --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2015/hardin/support --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2015/jain-manolios/support/memory-controller --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2015/jain-manolios/support/stack-machine --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2015/jain-manolios/support/vectorizing-transformation --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2017/coglio-kaufmann-smith/support --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2017/kaufmann-swords/support --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2017/sumners/support --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2017/swords/support --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2018/gamboa-cowles --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2018/greve-gacek --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2018/kaufmann --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2018/kwan-greenstreet --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2018/mehta --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2018/mehta/test --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2018/sumners --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2020/coglio-westfold --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2020/coglio-westfold/drone-plan --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2020/gamboa-cowles-gamboa --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2020/gamboa-cowles-gamboa/prior --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2020/greve --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2020/hardin --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2020/kwan-peng-greenstreet --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2020/mert --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2020/peng-greenstreet --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2020/peng-greenstreet/utils --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2020/sswords-mutual-ind --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2020/sswords-rewriter --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2020/sumners --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2022/gamboa-primitive-roots --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2022/kaufmann-moore --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2022/russinoff-calendar --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2022/russinoff-groups --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2022/stobj-tables --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2022/walter-manolios --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2022/walter-manolios/acl2s-utils --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2022/walter-manolios/examples --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2022/young-asymptotic --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2023/coglio-mccarthy-smith --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2023/hardin --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2023/kaufmann-moore --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2023/kumar-etal --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2023/kumar-etal/attacks --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2023/kwan --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2023/kwan-xin-young --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2023/passmore --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2023/vonhippel-etal --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2023/walter-etal --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2023/walter-etal/examples/ind-examples/pass --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2025 --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2025/kumar-manolios --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2025/kwan --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2025/kwan/extensions --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2025/kwan/instructions --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2025/manjrekar --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2025/manjrekar/examples/imul64 --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2025/manjrekar/examples/imul8 --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2025/medley-manolios --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2025/walter-manolios --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2025/walter-manolios/examples --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2025/walter-manolios/examples/acl2-demos --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2025/walter-manolios/examples/acl2s --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2025/walter-manolios/src/ffi --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2025/walter-manolios/src/z3 --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/workshops/2025/walter-manolios/test --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/xdoc --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir books/xdoc/tests --no-recurse
python scripts/summarize_kg.py --version v3-groq-gpt-oss-20b --source-dir doc --no-recurse
